### ISSUE TITLE
hash issues

### ISSUE THREAD

**Issue by ZanderFrieze** [WhiskyTangoFawks/LunarFalloutPlus#264]
I have tried at least 20 times to install this mod through wabbajack, with 15ish times doing an overwrite install and nearly a dozen times deleting all files in the install location, and also all files in the download location.  Once it is done with all the downloads and starts the install this is what is shown in the log.

05:22:26.266 [WARN] (Wabbajack.InstallerVM) While loading slide|System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Wabbajack.InstallerVM.PopulateNextModSlide(ModList modList) in c:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Installers\InstallerVM.cs:line 510
05:22:27.994 [INFO] (Wabbajack.Installer.StandardInstaller) Writing inline files
05:22:28.003 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Installing Included Files
05:22:28.269 [ERROR] (Wabbajack.Installer.StandardInstaller) Hashes for profiles\Life in the Ruins\plugins.txt did not match, expected 0FtwwxULeV0= got y6mQ+FHCxQE=
05:22:28.657 [ERROR] (Wabbajack.Installer.StandardInstaller) Hashes for profiles\Life in the Ruins - CreationClubPaints\loadorder.txt did not match, expected kbRfuDsTvdw= got q6844rBoWkA=
05:22:28.858 [ERROR] (Wabbajack.Installer.StandardInstaller) Hashes for profiles\Life in the Ruins\archives.txt did not match, expected y9gPHno1M9A= got gfOymsa4Lbk=
05:22:28.978 [ERROR] (Wabbajack.Installer.StandardInstaller) Hashes for profiles\Life in the Ruins - CreationClubPaints\plugins.txt did not match, expected 25XoAydgNfs= got kj1Pbsd+FO4=
05:22:29.062 [ERROR] (Wabbajack.Installer.StandardInstaller) Hashes for profiles\Life in the Ruins\loadorder.txt did not match, expected b5GpfJ8FPBk= got LnkASeoQYr4=
05:22:29.251 [ERROR] (Wabbajack.InstallerVM) Hashes for profiles\Life in the Ruins\plugins.txt did not match, expected 0FtwwxULeV0= got y6mQ+FHCxQE=|System.Exception: Hashes for profiles\Life in the Ruins\plugins.txt did not match, expected 0FtwwxULeV0= got y6mQ+FHCxQE=
   at Wabbajack.Installer.AInstaller`1.ThrowNonMatchingError(Directive file, Hash gotHash) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 298
   at Wabbajack.Installer.StandardInstaller.<>c__DisplayClass9_0.<<InstallIncludedFiles>b__0>d.MoveNext() in c:\oss\wabbajack\Wabbajack.Installer\StandardInstaller.cs:line 359
--- End of stack trace from previous location ---
   at Wabbajack.Common.AsyncParallelExtensions.PDoAll[TIn](IEnumerable`1 coll, Func`2 mapFn) in c:\oss\wabbajack\Wabbajack.Common\AsyncParallelExtensions.cs:line 15
   at Wabbajack.Installer.StandardInstaller.InstallIncludedFiles(CancellationToken token) in c:\oss\wabbajack\Wabbajack.Installer\StandardInstaller.cs:line 337
   at Wabbajack.Installer.StandardInstaller.Begin(CancellationToken token) in c:\oss\wabbajack\Wabbajack.Installer\StandardInstaller.cs:line 135
   at Wabbajack.InstallerVM.<BeginInstall>b__120_0() in c:\oss\wabbajack\Wabbajack.App.Wpf\View Models\Installers\InstallerVM.cs:line 441

**Comment by WhiskyTangoFawks** [comment]
This is an issue with the current release of wabbajack, nothing to do with the list itself, the solution is to manually download and use wabbajack  3.0.2.3 . Jump on our discord and someone there can help, if you need more assistance.
